### ISSUE TITLE
Display a back to top arrow on scroll not working in Customizr Pro 1.1.10 and Customizr 3.3.27

### ISSUE THREAD

**Issue by giorgioriccardi** [Nikeo/customizr#194]
The "Display a back to top arrow on scroll" option is not triggering the class .show anymore in Customizr Pro 1.1.10 and Customizr 3.3.27

I'm not sure if the problem is here:
https://github.com/Nikeo/customizr/blob/01e34e16e76904b93d65bc87cbd6ea9600a4898c/inc/assets/js/parts/main.js
because when I scroll down on the page I get this log error:
TypeError: f.className.indexOf is not a function
.../wp-includes/js/wp-emoji-release.min.js?ver=4.2.2
Line 4
etc. etc.

Customizr is running on a fresh clean WP 4.2.2 version, nothing else is installed. I'll try to figure out tomorrow

**Comment by eri-trabiccolo** [comment]
Hello Giorgio,
thanks for reporting this, yep back to top isn't displayed.
That error, anyway, shouldn't be related to the back to top arrow. It happens when you have featured pages with no images, so when you display the holder. Also it should happen with Customizr-Pro and not with Customizr 3.3.27 free.

**Comment by giorgioriccardi** [comment]
I double checked and it was not working with 3.3.27!
Works into 3.3.28, obviously ;-)

**Comment by eri-trabiccolo** [comment]
Hello giorgio:
"That error, anyway, shouldn't be related to the back to top arrow. It happens when you have featured pages with no images, so when you display the holder. Also it should happen with Customizr-Pro and not with Customizr 3.3.27 free."

I meant, the error you reported:
TypeError: f.className.indexOf is not a function
.../wp-includes/js/wp-emoji-release.min.js?ver=4.2.2

should not happen with 3.3.27.
And as I said was totally unrelated to the btt-arrow issue ;)

**Comment by giorgioriccardi** [comment]
Got it, that happens when I try to read fast, I focus on the straw without seeing the tree

**Comment by eri-trabiccolo** [comment]
:D 
You cannot read my English fast!!! :D
